# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rank_asR <- function(x, decreasing = FALSE) {
    .Call(`_GA_rank_asR`, x, decreasing)
}

which_asR <- function(x) {
    .Call(`_GA_which_asR`, x)
}

c_int <- function(x, y) {
    .Call(`_GA_c_int`, x, y)
}

c_double <- function(x, y) {
    .Call(`_GA_c_double`, x, y)
}

setdiff_asR <- function(x, y) {
    .Call(`_GA_setdiff_asR`, x, y)
}

intersect_asR <- function(x, y) {
    .Call(`_GA_intersect_asR`, x, y)
}

round_double <- function(x, n) {
    .Call(`_GA_round_double`, x, n)
}

ga_lrSelection_Rcpp <- function(object, r = NA_real_, q = NA_real_) {
    .Call(`_GA_ga_lrSelection_Rcpp`, object, r, q)
}

ga_nlrSelection_Rcpp <- function(object, q = NA_real_) {
    .Call(`_GA_ga_nlrSelection_Rcpp`, object, q)
}

ga_rwSelection_Rcpp <- function(object) {
    .Call(`_GA_ga_rwSelection_Rcpp`, object)
}

ga_tourSelection_Rcpp <- function(object, k = NA_real_) {
    .Call(`_GA_ga_tourSelection_Rcpp`, object, k)
}

ga_spCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_ga_spCrossover_Rcpp`, object, parents)
}

gabin_Population_Rcpp <- function(object) {
    .Call(`_GA_gabin_Population_Rcpp`, object)
}

gabin_uCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gabin_uCrossover_Rcpp`, object, parents)
}

gabin_raMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gabin_raMutation_Rcpp`, object, parent)
}

gareal_Population_Rcpp <- function(object) {
    .Call(`_GA_gareal_Population_Rcpp`, object)
}

gareal_lsSelection_Rcpp <- function(object) {
    .Call(`_GA_gareal_lsSelection_Rcpp`, object)
}

gareal_sigmaSelection_Rcpp <- function(object) {
    .Call(`_GA_gareal_sigmaSelection_Rcpp`, object)
}

gareal_waCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gareal_waCrossover_Rcpp`, object, parents)
}

gareal_laCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gareal_laCrossover_Rcpp`, object, parents)
}

gareal_blxCrossover_Rcpp <- function(object, parents, a) {
    .Call(`_GA_gareal_blxCrossover_Rcpp`, object, parents, a)
}

gareal_laplaceCrossover_Rcpp <- function(object, parents, a, b) {
    .Call(`_GA_gareal_laplaceCrossover_Rcpp`, object, parents, a, b)
}

gareal_raMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gareal_raMutation_Rcpp`, object, parent)
}

gareal_nraMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gareal_nraMutation_Rcpp`, object, parent)
}

gareal_rsMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gareal_rsMutation_Rcpp`, object, parent)
}

gareal_powMutation_Rcpp <- function(object, parent, pow) {
    .Call(`_GA_gareal_powMutation_Rcpp`, object, parent, pow)
}

gaperm_Population_Rcpp <- function(object) {
    .Call(`_GA_gaperm_Population_Rcpp`, object)
}

gaperm_cxCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gaperm_cxCrossover_Rcpp`, object, parents)
}

gaperm_pmxCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gaperm_pmxCrossover_Rcpp`, object, parents)
}

gaperm_oxCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gaperm_oxCrossover_Rcpp`, object, parents)
}

gaperm_pbxCrossover_Rcpp <- function(object, parents) {
    .Call(`_GA_gaperm_pbxCrossover_Rcpp`, object, parents)
}

gaperm_simMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gaperm_simMutation_Rcpp`, object, parent)
}

gaperm_ismMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gaperm_ismMutation_Rcpp`, object, parent)
}

gaperm_swMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gaperm_swMutation_Rcpp`, object, parent)
}

gaperm_dmMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gaperm_dmMutation_Rcpp`, object, parent)
}

gaperm_scrMutation_Rcpp <- function(object, parent) {
    .Call(`_GA_gaperm_scrMutation_Rcpp`, object, parent)
}

ga_pmutation_Rcpp <- function(object, p0 = NA_real_, p = NA_real_, T = NA_real_) {
    .Call(`_GA_ga_pmutation_Rcpp`, object, p0, p, T)
}

optimProbsel_Rcpp <- function(x, q = NA_real_) {
    .Call(`_GA_optimProbsel_Rcpp`, x, q)
}

gareal_de_Rcpp <- function(object, fitness, F = NA_real_, p = NA_real_) {
    .Call(`_GA_gareal_de_Rcpp`, object, fitness, F, p)
}

